name: deploy
on:
  push:
    branches:
      - main
      - deployment-pipeline
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt install ruby
          gem install dpl-heroku
      - name: deploy to Heroku
        run: dpl --provider=heroku --app=nlp-timeline-gen --api-key={{ secrets.HEROKU_API_KEY }}
