name: check and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      secretkey: ${{ secrets.FLASK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: ./scripts/setup.sh
      - name: Lint python files with flake8
        run: ./scripts/check_py_format.sh
      - name: Test with pytest
        run: ./scripts/run_py_tests.sh
  prod-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: |
          cd client
          sudo apt install npm
          npm install
          npm install gh-pages --save-dev
      - name: production deploy to Github pages
        run: |
          cd client
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions' 
          git remote set-url origin https://${{ secrets.PAT }}@github.com/JamesLee-Jones/ChronoLog.git 
          npm run deploy
