name: check and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      secretkey: ${{ secrets.FLASK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: ./scripts/setup.sh
      - name: Lint python files with flake8
        run: ./scripts/check_py_format.sh
      - name: Test with pytest
        run: ./scripts/run_py_tests.sh
  heroku-staging-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt install ruby
          sudo gem install dpl-heroku
      - name: add Flask secret key
        run: echo "secretkey = \"${{ secrets.FLASK_SECRET_KEY }}\"" > .env
      - name: staging deploy to Heroku
        run: dpl --provider=heroku --app=nlp-timeline-gen-staging --api-key=${{ secrets.HEROKU_API_KEY }}
  heroku-prod-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt install ruby
          sudo gem install dpl-heroku
      - name: production deploy to Heroku
        run: dpl --provider=heroku --app=nlp-timeline-gen-prod --api-key=${{ secrets.HEROKU_API_KEY }}
